name: spice_dispenser_app
description: "Professional Flutter app for Spice Dispenser control"

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

ions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Connectivity & Hardware
  flutter_blue_plus: ^1.31.0
  permission_handler: ^11.3.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Utilities & JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
